# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ph7yhnCZIvT_lYyt4_SQhOtmNd9mWe6u
"""

import pandas as pd
df = pd.read_csv('VENDAS.csv')



import requests
import json
import csv

with open ('VENDAS.csv', mode='r') as arquivo_csv:
  leitor = csv.DictReader(arquivo_csv)
  for linha in leitor:
    print (linha)

def calcular_total[vendas]:
return vendas['vr unit'] * vendas[qtde]

totais  = map(calcular_total, vendas)
print(sum(totais))

def carregar_dados(dados, arquivo_saida):
  with open(arquivo_saida, 'w', newline='') as arquivo_csv:
    nomes_campos = ['Produto', 'vr unit', 'qtde vendidas']
    escritor = csv.DictWriter(arquivo_csv, fieldnames=nomes_campos)
    escritor.writeheader()
    escritor.writerows(dados)

if __name__ == "__main__":
   arquivo_entrada = 'vendas.csv'
   arquivo_saida = 'Total_vendas.csv'

print ("arquivo salvo", arquivo_saida)

